import Foundation
import AppKit

/// Implements the community `nspasteboard.org` convention: clipboard managers
/// must skip items that carry any of these "don't store me" marker UTIs.
///
/// Password managers (1Password, Dashlane, Bitwarden), temporary-clipboard
/// tools, and Universal Clipboard all rely on this. Honoring it is table
/// stakes for a user-trustable clipboard history tool.
public enum TransientFilter {
    public static let skipUTIs: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.ConcealedAutoGeneratedType",
        "com.agilebits.onepassword",                        // legacy 1Password marker
        "de.petersteinberger.pasteboard.dontsave",          // legacy marker
    ]

    /// Returns true if any item in the array carries a skip marker.
    public static func shouldSkip(_ items: [NSPasteboardItem]) -> Bool {
        for item in items {
            for type in item.types {
                if skipUTIs.contains(type.rawValue) { return true }
            }
        }
        return false
    }
}
