import XCTest
@testable import CpdbShared

/// Canonical-hash vectors.
///
/// `testV2PinnedVectors` is JSON-driven: it loads the authoritative
/// `Tests/Fixtures/hash-vectors-v2.json` (generated by
/// `Tools/gen_hash_vectors.py`, the cross-platform reference implementation)
/// and asserts that `ContentIdentity` reproduces every `expect_tag` /
/// `expect_hex`. The same JSON file is consumed by the Windows port's
/// `CanonicalHashTests.cs`, so Swift and C# are pinned to one source of truth.
///
/// `testV1HistoricalVectors` keeps the old full-flavor-set hash pinned — it is
/// still computed for the dual-era importer probe during the v2 migration.
final class HashVectors: XCTestCase {

    // MARK: - v2 (semantic content identity) — JSON-driven

    struct VectorFile: Decodable {
        let identity_revision: String
        let vectors: [Vector]
    }
    struct Vector: Decodable {
        let name: String
        let note: String
        let items: [[FlavorJSON]]
        let expect_tag: String
        let expect_hex: String
        let equals: String?
    }
    struct FlavorJSON: Decodable {
        let uti: String
        let base64: String
    }

    /// Canonical fixture path, resolved from this source file's location so the
    /// single JSON serves both platforms (no SPM resource duplication).
    /// `<repo>/Tests/CpdbCoreTests/HashVectors.swift` → `<repo>/Tests/Fixtures/…`.
    private func fixtureURL() -> URL {
        URL(fileURLWithPath: #filePath)        // .../Tests/CpdbCoreTests/HashVectors.swift
            .deletingLastPathComponent()       // .../Tests/CpdbCoreTests
            .deletingLastPathComponent()       // .../Tests
            .appendingPathComponent("Fixtures/hash-vectors-v2.json")
    }

    func testV2PinnedVectors() throws {
        let url = fixtureURL()
        let data = try Data(contentsOf: url)
        let file = try JSONDecoder().decode(VectorFile.self, from: data)
        XCTAssertEqual(file.identity_revision, ContentIdentity.revision,
                       "fixture revision must match the implementation revision")
        XCTAssertGreaterThan(file.vectors.count, 20, "fixture looks truncated")

        var hashByName: [String: String] = [:]
        for v in file.vectors {
            let items: [[CanonicalHash.Flavor]] = v.items.map { item in
                item.map { f in
                    CanonicalHash.Flavor(uti: f.uti,
                                         data: Data(base64Encoded: f.base64) ?? Data())
                }
            }
            let (tag, hash) = ContentIdentity.compute(items: items)
            let hex = CanonicalHash.hex(hash)

            XCTAssertEqual(tag.rawValue, v.expect_tag, "tag mismatch for vector '\(v.name)' (\(v.note))")
            XCTAssertEqual(hex, v.expect_hex, "hash mismatch for vector '\(v.name)' (\(v.note))")

            if let eq = v.equals, let want = hashByName[eq] {
                XCTAssertEqual(hex, want, "equals-relation broken: '\(v.name)' should equal '\(eq)'")
            }
            hashByName[v.name] = hex
        }
    }

    /// Spot-check a couple of rung outcomes directly, independent of the JSON,
    /// so a corrupted fixture can't make the suite vacuously pass.
    func testV2RungSpotChecks() {
        // image wins over url/text sidecars
        let png = Data([0x89, 0x50, 0x4E, 0x47]) + Data(repeating: 0xAB, count: 2000)
        let imgItems: [[CanonicalHash.Flavor]] = [[
            .init(uti: "public.url", data: Data("https://x".utf8)),
            .init(uti: "public.png", data: png),
        ]]
        XCTAssertEqual(ContentIdentity.compute(items: imgItems).tag, .image)

        // sub-threshold png falls through to fallback
        let tiny: [[CanonicalHash.Flavor]] = [[.init(uti: "public.png", data: Data([0x89, 0x50]))]]
        XCTAssertEqual(ContentIdentity.compute(items: tiny).tag, .fallback)

        // bare URL text promotes
        let promo: [[CanonicalHash.Flavor]] = [[.init(uti: "public.utf8-plain-text", data: Data("https://x.com\n".utf8))]]
        XCTAssertEqual(ContentIdentity.compute(items: promo).tag, .url)

        // URL mid-sentence does NOT promote
        let neg: [[CanonicalHash.Flavor]] = [[.init(uti: "public.utf8-plain-text", data: Data("see https://x.com now".utf8))]]
        XCTAssertEqual(ContentIdentity.compute(items: neg).tag, .text)

        // rung index ordering is monotonic (image most-authoritative)
        XCTAssertLessThan(ContentIdentity.Tag.image.rungIndex, ContentIdentity.Tag.url.rungIndex)
        XCTAssertLessThan(ContentIdentity.Tag.url.rungIndex, ContentIdentity.Tag.fallback.rungIndex)
    }

    // MARK: - v1 (historical full-flavor-set hash) — still used for the dual-era probe

    func testV1HistoricalVectors() {
        let v1: [[CanonicalHash.Flavor]] = [[
            .init(uti: "public.utf8-plain-text", data: Data("hello".utf8))
        ]]
        XCTAssertEqual(CanonicalHash.hex(CanonicalHash.hash(items: v1)),
            "b22187611777c1e9c84c3fdd054ed311a47d12f33cba6d1e7761bd3a7314073a")

        let v2: [[CanonicalHash.Flavor]] = [[
            .init(uti: "public.utf8-plain-text", data: Data("hello".utf8)),
            .init(uti: "public.html", data: Data("<b>hello</b>".utf8)),
        ]]
        XCTAssertEqual(CanonicalHash.hex(CanonicalHash.hash(items: v2)),
            "17a95cac0686665cfe5342a3a041d7afedfa4c14a59d6d3c6b7b53a4bf0ad85a")
    }
}
