// swift-tools-version:5.10
import Foundation
import PackageDescription

// `make build-app` needs `appintentsmetadataprocessor` (the tool that
// makes App Intents/App Shortcuts discoverable to Shortcuts/Siri/
// Spotlight) to run against CpdbApp, but that tool is normally an
// Xcode build-phase, invisible to plain `swift build`. The flag pair
// below makes the Swift frontend emit the `.swiftconstvalues` file the
// processor needs. A single combined output only makes sense for a
// single frontend job over the whole target, which is exactly what
// SwiftPM's `-c release` already builds with (whole-module
// optimization) — this only activates for that build, gated behind an
// env var so the fast `swift build`/`swift test` dev-iteration loop
// (incremental, per-file jobs) is untouched.
// `scripts/build-app-intents-metadata.sh` sets both env vars and runs
// `appintentsmetadataprocessor` itself afterward.
let appIntentsConstValuesFlags: [SwiftSetting] = {
    let env = ProcessInfo.processInfo.environment
    guard env["CPDB_EXTRACT_APPINTENTS"] == "1",
          // Must be an absolute path: the frontend job's working
          // directory isn't guaranteed to be the package root, so a
          // relative path here silently writes nowhere findable
          // (verified empirically — no error, no file).
          let constValuesPath = env["CPDB_APPINTENTS_CONSTVALUES_PATH"],
          // `-const-gather-protocols-file` wants a bare JSON array of
          // protocol names — NOT the
          // `{"version":1,"constValueProtocols":[…]}` envelope Xcode's
          // own toolchain ships at
          // `usr/share/swift/SwiftConstantValues/AppIntents.json`;
          // feeding that file to this swiftc directly fails with
          // "... is malformed" (also verified empirically). The script
          // flattens it to this path before setting the env var.
          let protocolsFile = env["CPDB_APPINTENTS_PROTOCOLS_FILE"]
    else { return [] }
    return [.unsafeFlags([
        "-Xfrontend", "-emit-const-values-path",
        "-Xfrontend", constValuesPath,
        "-Xfrontend", "-const-gather-protocols-file",
        "-Xfrontend", protocolsFile,
    ])]
}()

let package = Package(
    name: "cpdb",
    platforms: [
        .macOS(.v14),
        .iOS(.v17),
    ],
    products: [
        // The macOS CLI is named `cpdb-cli` at the package level to
        // avoid colliding with the iOS app target (also `cpdb`) when
        // the iOS Xcode project consumes this repo as a Local Package.
        // The shipped binary is still `cpdb` — the Makefile renames it
        // during install (see `install-cli`).
        .executable(name: "cpdb-cli", targets: ["cpdb-cli"]),
        .executable(name: "CpdbApp", targets: ["CpdbApp"]),
        .library(name: "CpdbShared", targets: ["CpdbShared"]),
        .library(name: "CpdbCore", targets: ["CpdbCore"]),
    ],
    dependencies: [
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "6.29.0"),
        .package(url: "https://github.com/apple/swift-argument-parser.git", from: "1.5.0"),
        .package(url: "https://github.com/sindresorhus/KeyboardShortcuts.git", from: "2.4.0"),
        // Sparkle 2.x — in-app auto-update for the notarized
        // direct-download Mac build. Consumed only by CpdbApp;
        // the CLI + libraries don't link it. EdDSA-signed
        // appcast generated by `make appcast`.
        .package(url: "https://github.com/sparkle-project/Sparkle.git", from: "2.6.0"),
    ],
    targets: [
        .executableTarget(
            name: "cpdb-cli",
            dependencies: [
                "CpdbCore",
                "CpdbShared",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ],
            // Sources still live at Sources/cpdb — only the target/
            // product names changed. Keeping the path explicit lets
            // us rename without a directory move.
            path: "Sources/cpdb"
        ),
        .executableTarget(
            name: "CpdbApp",
            dependencies: [
                "CpdbCore",
                "CpdbShared",
                .product(name: "KeyboardShortcuts", package: "KeyboardShortcuts"),
                .product(name: "Sparkle", package: "Sparkle"),
            ],
            // Info.plist + entitlements + icon assets live under Resources/,
            // but SPM can't actually package a menu-bar app bundle — the
            // Makefile does that. Exclude these so SPM doesn't treat them
            // as Swift sources or untyped resources (which emits a build
            // warning for each file).
            exclude: [
                "Resources/Info.plist",
                "Resources/cpdb.entitlements",
                "Resources/cpdb-release.entitlements",
                "Resources/Assets",
            ],
            swiftSettings: appIntentsConstValuesFlags
        ),
        // Cross-platform library: pure data, GRDB storage, Vision analysis,
        // FTS5 search, Quick Look item building. iOS + macOS both link this.
        .target(
            name: "CpdbShared",
            dependencies: [
                .product(name: "GRDB", package: "GRDB.swift"),
            ]
        ),
        // macOS-only library: NSPasteboard plumbing, Paste.db import,
        // launchd helpers, daemon lock. Layers on top of CpdbShared.
        .target(
            name: "CpdbCore",
            dependencies: [
                "CpdbShared",
                .product(name: "GRDB", package: "GRDB.swift"),
            ]
        ),
        // The iOS companion app lives at iOS/cpdb/cpdb.xcodeproj
        // and depends on this package via Xcode's Local Package
        // feature (importing CpdbShared directly). Not defined as
        // an SPM target here because iOS apps need Xcode's full
        // build pipeline (Info.plist, asset catalog, entitlements,
        // code signing), which SPM's executableTarget doesn't
        // provide. Sources live under iOS/cpdb/cpdb/ — that's the
        // single source of truth.
        .testTarget(
            name: "CpdbCoreTests",
            dependencies: [
                "CpdbCore",
                "CpdbShared",
                .product(name: "GRDB", package: "GRDB.swift"),
            ]
            // Note: `swift test` needs a full Xcode toolchain for Testing.framework.
            // Run `DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer swift test`,
            // or set it once in your shell. `swift build` works with Command Line Tools alone.
        ),
        // Test target depending directly on the CpdbApp *executable*
        // target — supported by SwiftPM since Swift 5.5 (test targets
        // may depend on executables; `@testable import CpdbApp` works
        // under `swift test`'s debug build). Lets us exercise popup
        // layout code (PopupController/EntryStripView/EntryCard/
        // PopupRootView/AppState) without relocating it out of the app
        // target.
        .testTarget(
            name: "CpdbAppTests",
            dependencies: [
                "CpdbApp",
                "CpdbCore",
                "CpdbShared",
                .product(name: "GRDB", package: "GRDB.swift"),
            ]
        ),
    ]
)
