using System.Text.Json;
using System.Text.Json.Serialization;
using CpdbWin.Core.Capture;
using Xunit;

namespace CpdbWin.Core.Tests;

/// <summary>
/// JSON-driven theory over the authoritative cross-platform vectors at
/// <c>Tests/Fixtures/hash-vectors-v2.json</c> (generated by
/// <c>Tools/gen_hash_vectors.py</c>; the Swift port has a parallel
/// <c>HashVectors.swift</c> doing the same thing).
///
/// <para>
/// Every <c>expect_tag</c> + <c>expect_hex</c> must reproduce byte-for-byte;
/// every <c>equals</c> relation must hold. The handoff doc
/// (<c>docs/handoffs/windows-hash-v2.md</c>) calls this file out by name as
/// the contract: anything in the prose loses to the vectors JSON if they
/// disagree.
/// </para>
/// </summary>
public class ContentIdentityVectorsTests
{
    private const string VectorsRelativePath = "Fixtures/hash-vectors-v2.json";

    public sealed record VectorItemFlavor(
        [property: JsonPropertyName("uti")]    string Uti,
        [property: JsonPropertyName("base64")] string Base64);

    public sealed record Vector(
        [property: JsonPropertyName("name")]       string Name,
        [property: JsonPropertyName("note")]       string? Note,
        [property: JsonPropertyName("items")]      List<List<VectorItemFlavor>> Items,
        [property: JsonPropertyName("expect_tag")] string ExpectTag,
        [property: JsonPropertyName("expect_hex")] string ExpectHex,
        [property: JsonPropertyName("equals")]     string? EqualsName);

    public sealed record VectorsDoc(
        [property: JsonPropertyName("identity_revision")] string IdentityRevision,
        [property: JsonPropertyName("hash")]              string HashSpec,
        [property: JsonPropertyName("vectors")]           List<Vector> Vectors);

    private static VectorsDoc LoadDoc()
    {
        var path = Path.Combine(AppContext.BaseDirectory, VectorsRelativePath);
        Assert.True(File.Exists(path),
            $"hash-vectors-v2.json not copied to test output at {path}. "
          + "Check CpdbWin.Core.Tests.csproj's <None Include=... CopyToOutputDirectory> entry.");
        var json = File.ReadAllText(path);
        var doc = JsonSerializer.Deserialize<VectorsDoc>(json,
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        Assert.NotNull(doc);
        return doc!;
    }

    /// <summary>
    /// Provider for <see cref="ProducesExpectedTagAndHash"/> — yields one
    /// row per JSON vector. xUnit takes the names from <c>v.Name</c>.
    /// </summary>
    public static IEnumerable<object[]> AllVectors()
    {
        foreach (var v in LoadDoc().Vectors) yield return new object[] { v };
    }

    [Theory]
    [MemberData(nameof(AllVectors))]
    public void ProducesExpectedTagAndHash(Vector v)
    {
        var items = v.Items.Select(item =>
            (IReadOnlyList<CanonicalHash.Flavor>)item.Select(f =>
                new CanonicalHash.Flavor(f.Uti, Convert.FromBase64String(f.Base64))).ToList()
        ).ToList();

        var (tag, hash) = ContentIdentity.Compute(items);
        Assert.Equal(v.ExpectTag, ContentIdentity.TagString(tag));
        Assert.Equal(v.ExpectHex, CanonicalHash.ToHex(hash));
    }

    /// <summary>
    /// Cross-check every <c>equals</c> relation in one shot: two vectors
    /// linked by <c>equals: name</c> must produce identical hashes. This
    /// catches a wrong-rung port that happens to match isolated hexes but
    /// breaks the convergence story the v2 design is named after.
    /// </summary>
    [Fact]
    public void EqualsRelationsHold()
    {
        var doc = LoadDoc();
        var byName = doc.Vectors.ToDictionary(v => v.Name, v => v);
        var failures = new List<string>();
        foreach (var v in doc.Vectors)
        {
            if (v.EqualsName is null) continue;
            Assert.True(byName.ContainsKey(v.EqualsName),
                $"vector {v.Name} references unknown equals target {v.EqualsName}");
            var target = byName[v.EqualsName];
            if (!string.Equals(v.ExpectHex, target.ExpectHex, StringComparison.OrdinalIgnoreCase))
                failures.Add($"{v.Name} equals {v.EqualsName}: JSON says {v.ExpectHex} vs {target.ExpectHex} — vectors file itself is inconsistent");
        }
        Assert.Empty(failures);
    }

    [Fact]
    public void IdentityRevisionMatchesPort()
    {
        Assert.Equal(ContentIdentity.Revision, LoadDoc().IdentityRevision);
    }
}
