import AppKit
import Sparkle
import CpdbShared

/// Owns the Sparkle updater for the direct-download (non-App-Store)
/// Mac build. Feed URL + EdDSA public key live in Info.plist
/// (`SUFeedURL`, `SUPublicEDKey`); the appcast is generated by
/// `make appcast` and shipped as a GitHub release asset.
///
/// `SUEnableAutomaticChecks = true` + `SUScheduledCheckInterval =
/// 86400` means a background check once a day. `SUAutomaticallyUpdate
/// = false` means we *prompt* rather than silently swap — right for
/// a menu-bar utility the user rarely quits, since a silent
/// install-on-quit could sit pending for weeks.
///
/// The CLI + libraries never link Sparkle — only this CpdbApp file
/// imports it, so the headless `cpdb` binary stays dependency-free.
@MainActor
final class UpdaterController: NSObject {
    static let shared = UpdaterController()

    private let controller: SPUStandardUpdaterController

    private override init() {
        // startingUpdater: true kicks off the scheduled-check timer
        // immediately. We pass nil delegates — the Info.plist keys
        // cover everything we need; no custom appcast filtering or
        // version-comparison logic.
        controller = SPUStandardUpdaterController(
            startingUpdater: true,
            updaterDelegate: nil,
            userDriverDelegate: nil
        )
        super.init()
    }

    /// Start the updater. Calling the lazy `shared` is enough —
    /// `SPUStandardUpdaterController(startingUpdater: true)` already
    /// armed the timer in init. This exists so `AppDelegate` can
    /// make the intent explicit at launch and log it.
    func start() {
        Log.cli.info("sparkle updater armed (feed in Info.plist, daily check)")
    }

    /// User-initiated "Check for Updates…" from the menu. Sparkle
    /// shows its own progress / "you're up to date" / "update
    /// available" UI from here.
    @objc func checkForUpdates() {
        controller.checkForUpdates(nil)
    }

    /// Whether the menu item should be enabled — Sparkle disables
    /// it while a check is already in flight.
    var canCheckForUpdates: Bool {
        controller.updater.canCheckForUpdates
    }
}
