import Foundation

/// Cross-platform "don't store me" guard, evaluated against a decoded
/// `PasteboardSnapshot` rather than an `NSPasteboardItem`/`UIPasteboard`.
///
/// This is the CpdbShared home that hash-v2 §3 ("Capture-time changes")
/// calls for: the `nspasteboard.org` transient/concealed markers must move
/// from the macOS-only `TransientFilter` watcher into CpdbShared and be
/// enforced *at the ingest entry point* as a whole-snapshot rejection, so
/// that **iOS and any future capture path inherit them**. Under hash-v2 a
/// leaked concealed capture would otherwise bump an existing visible entry
/// fleet-wide (semantic identity) instead of forking deletably — so the
/// guard has to live below the platform pasteboard layer.
///
/// For THIS pass the marker set is the same one `CpdbCore/TransientFilter`
/// uses on macOS; it's duplicated here intentionally (the macOS watcher
/// still checks `NSPasteboardItem.types` *before* it copies the bytes, which
/// is strictly better than waiting for a decoded snapshot). The shared copy
/// is the **seam** hash-v2 §3 will wire the canonical set into — see
/// `CpdbCore/Capture/TransientFilter.swift` for the macOS source of truth
/// that should eventually fold into this type.
///
/// iOS note: `UIPasteboard` does not surface arbitrary custom UTIs the way
/// `NSPasteboard` does, and password managers on iOS mark items via
/// `UIPasteboard`'s own privacy mechanisms rather than these macOS marker
/// UTIs. The shared set therefore rarely fires on iOS today; it exists so
/// that (a) the entry point is honest about intent, and (b) when hash-v2
/// lands the canonical never-store set, iOS gets it for free. The iOS
/// capture controller layers `detectPatterns`/`looksLikeApplePassword` on
/// top — see `IOSClipboardCapture`.
public enum TransientGuard {
    /// UTIs whose presence means "a clipboard manager must not retain this".
    /// Mirrors `nspasteboard.org` plus a couple of legacy password-manager
    /// markers. Kept in sync with `CpdbCore.TransientFilter.skipUTIs`.
    public static let concealedUTIs: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.ConcealedAutoGeneratedType",
        "com.agilebits.onepassword",               // legacy 1Password marker
        "de.petersteinberger.pasteboard.dontsave", // legacy marker
    ]

    /// Whole-snapshot rejection: true iff any flavor on any item carries a
    /// concealed/transient marker UTI. Call this at the ingest entry point
    /// before computing identity or writing anything.
    public static func shouldReject(_ snapshot: PasteboardSnapshot) -> Bool {
        for item in snapshot.items {
            for flavor in item.flavors where concealedUTIs.contains(flavor.uti) {
                return true
            }
        }
        return false
    }
}
