#!/usr/bin/env bash
# stamp-build.sh — write the current git short-sha into BuildStamp.swift.
#
# Called by the Makefile before `swift build` so the resulting binary
# identifies itself as e.g. "2.0.0-dev+9e59148". Idempotent — if the
# working tree's stamp is already current, the file isn't rewritten
# (keeps `swift build` fast).
#
# If the working tree is dirty (uncommitted changes), appends `-dirty`
# so you can tell "exactly this commit" from "this commit + tweaks."

set -euo pipefail

STAMP_FILE="Sources/CpdbShared/BuildStamp.swift"

# Resolve short sha. Fallback to `unknown` if we're not in a git
# checkout (shouldn't happen for the normal dev flow, but keeps the
# script well-behaved if the repo was downloaded as a zip).
if sha=$(git rev-parse --short HEAD 2>/dev/null); then
    if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
        sha="${sha}-dirty"
    fi
else
    sha="unknown"
fi

# Skip the write if the stamp is already correct — avoids cache busts
# on every build.
current=$(grep -E 'static let stamp = ' "$STAMP_FILE" | sed -E 's/.*"([^"]*)".*/\1/')
if [[ "$current" == "$sha" ]]; then
    exit 0
fi

cat > "$STAMP_FILE" <<EOF
/// Build stamp — generated by scripts/stamp-build.sh.
/// Do not edit by hand; changes will be overwritten on next build.
enum BuildStamp {
    static let stamp = "$sha"
}
EOF

echo "stamped BuildStamp.swift: $sha"
